const burgersData = [
  {
    image: "../assets/images/1.png",
    title: "Cheddar & Bacon Burger",
    text: "Crispy beef patty, bun, tomato, Cheddar cheese, bacon, red onion, iceberg lettuce, mayonnaise, ketchup, cheese sauce",
    price: 8,
    gramms: 360,
    basePrice: 8,
  },
  {
    image: "../assets/images/2.png",
    title: "BBQ Burger with Bacon and Chicken",
    text: "Brioche bun with sesame seeds, chicken patty, Cheddar cheese, tomato, pickled cucumber, pickled onion, Romaine lettuce, bacon, BBQ sauce",
    price: 7,
    gramms: 390,
    basePrice: 7,
  },
  {
    image: "../assets/images/3.png",
    title: "Double Beef Burger",
    text: "Two beef patties, Cheddar cheese, romaine lettuce, pickled cucumbers, fresh tomato, bacon, red onion, burger sauce, mustard",
    price: 10,
    gramms: 420,
    basePrice: 10,
  },
  {
    image: "../assets/images/4.png",
    title: "Bavarian Burger",
    text: "Burger bun, beef patty, red onion, cheese, hunter sausage, BBQ sauce, cheese sauce, iceberg lettuce",
    price: 7,
    gramms: 220,
    basePrice: 7,
  },
  {
    image: "../assets/images/5.png",
    title: "Bacon Cheeseburger",
    text: "Burger bun, beef patty, bacon, tomato, pickled cucumber, cheese, cheese sauce, ketchup, greens",
    price: 8,
    gramms: 220,
    basePrice: 8,
  },
  {
    image: "../assets/images/6.png",
    title: "Indiana Burger",
    text: "Burger bun, chicken patty, bacon, egg, pickled cucumber, crispy onion, ketchup, cheese sauce, mustard, greens",
    price: 9,
    gramms: 320,
    basePrice: 9,
  },
  {
    image: "../assets/images/7.png",
    title: "Veggie Burger",
    text: "Burger bun, vegetarian patty, red onion, cheese, fresh tomato, BBQ sauce, cheese sauce, iceberg lettuce",
    price: 8,
    gramms: 280,
    basePrice: 8,
  },
  {
    image: "../assets/images/8.png",
    title: "Whiny Joe Burger",
    text: "Burger bun, beef patty, bacon, tomato, pickled cucumber, red onion, cheese, jalapeño pepper, ketchup, greens",
    price: 7,
    gramms: 380,
    basePrice: 7,
  },
  {
    image: "../assets/images/9.png",
    title: "Double Cheeseburger",
    text: "Burger bun, two beef patties, double Cheddar cheese, pickled cucumber, crispy onion, ketchup, cheese sauce, mustard, greens",
    price: 11,
    gramms: 400,
    basePrice: 11,
  },
  {
    image: "../assets/images/10.png",
    title: "Fresh Burger",
    text: "Burger bun, beef patty, bacon, Cheddar cheese, egg, salami, BBQ sauce, cheese sauce, iceberg lettuce, fresh tomato",
    price: 9,
    gramms: 300,
    basePrice: 9,
  },
  {
    image: "../assets/images/11.png",
    title: "Zucchini Burger",
    text: "Burger bun, vegetarian chickpea patty, grilled zucchini, tomato, pickled cucumber, cheese, mustard sauce, ketchup, greens",
    price: 8,
    gramms: 320,
    basePrice: 8,
  },
  {
    image: "../assets/images/12.png",
    title: "Double Cheddar Burger",
    text: "Burger bun, beef patty, bacon, red onion, pickled cucumber, tomato, ketchup, double Cheddar cheese, mustard, greens",
    price: 9,
    gramms: 360,
    basePrice: 9,
  },
];

module.exports = burgersData;
